### ISSUE TITLE
"horizontal" should be "vertical"

### ISSUE THREAD

**Issue by jmarkowi** [learn-co-curriculum/dsc-intro-to-sets#4]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/4244/pages/introduction-to-sets?module_item_id=283524

## What should be changed?

Currently the text says: "where the horizontal lines denote the cardinality of a set, which is the number of elements in the set, considering a set with a finite number of elements."

I believe it should say: "where the **vertical** lines denote..." 

## Additional context

This seems like a pretty crucial error that has the potential to generate a lot of confusion since it's on the first big explanation of sets.

**Comment by bpurdy-ds** [comment]
The horizontal/vertical has been fixed. And this page for the next push of the blueprints looks much better overall.
