### ISSUE TITLE
Small terminology error. Probably

### ISSUE THREAD

**Issue by FerdinandBeaman** [learn-co-curriculum/dsc-intro-to-sets#5]
## Link to Canvas

https://learning.flatironschool.com/courses/4348/pages/introduction-to-sets?module_item_id=293295

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x] Instructions unclear
- [ ] Other (explain below)

## Describe the Issue
Under the subheading "Inclusion-Exclusion Principle", the module makes reference to horizontal lines but I'm pretty sure they mean vertical lines.

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by bpurdy-ds** [comment]
The horizontal/vertical has been fixed. And this page for the next push of the blueprints looks much better overall.
