### ISSUE TITLE
two mistakes in the Introduction to Sets lesson of phase 2, data science flex

### ISSUE THREAD

**Issue by MNLKuzmin** [learn-co-curriculum/dsc-intro-to-sets#6]
## Link to Canvas

https://learning.flatironschool.com/courses/5316/pages/introduction-to-sets?module_item_id=408277

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [X] Instructions unclear
- [ ] Other (explain below)

### Source

```
Example: If S is the set of even numbers, set is a proper subset of . Formally, you can write this as . 
is also correct in this case!

SECOND issue:
When having two sets, the method for counting the number of elements in the union of two finite sets is given by:

,

where the horizontal lines denote the cardinality of a set, which is the number of elements in the set, considering a set with a finite number of elements.
```

### Concern

This statements about the sets is either unclear or incorrect. 
the second issue: it says the horizontal lines, I believe it means the vertical lines?
<img width="1028" alt="Screen Shot 2022-07-25 at 12 24 37 PM" src="https://user-images.githubusercontent.com/103147944/180756398-d0d5cae9-2585-4a8c-8b36-ba2b8160700f.png">
<img width="1028" alt="Screen Shot 2022-07-25 at 12 28 14 PM" src="https://user-images.githubusercontent.com/103147944/180756426-8c335883-2c1a-484a-b853-548babfd4ce8.png">

## (Optional) Proposed Solution

It would be correct if the S set is 2, 6, 22, but that is not specified.
For the second issue, it's simply vertical lines instead of horizontal.

## What OS Are You Using?

- [X] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by bpurdy-ds** [comment]
The horizontal/vertical has been fixed. And this page for the next push of the blueprints looks much better overall.
Unless I am misunderstanding the point, both proper subset and the subset symbol are valid for T being contained in S in the same we can write 2 is less than 3 or 2 is less than or equal to 3.
